export const ADD_CART = 'ADD_CART'
export const EDIT_CART = 'EDIT_CART'
export const REMOVE_CART = 'REMOVE_CART'
export const UPDATE_QUANTITY = 'UPDATE_QUANTITY'
export const ADD_FAVORITE = 'ADD_FAVORITE'