export const ADD_CART = "ADD_CART";
export const REMOVE_CART = "REMOVE_CART";
export const UPDATE_QUANTITY = "UPDATE_QUANTITY";
export const ADD_FAVORITE = "ADD_FAVORITE";
export const CART_TO_ORDERLATER = "CART_TO_ORDERLATER";
export const UPDATE_LIST_CART = "FETCH_CART";
