export const ADD_CART = 'ADD_CART'
export const REMOVE_CART = 'REMOVE_CART'
export const UPDATE_QUANTITY = 'UPDATE_QUANTITY'
export const UPDATE_LIST_CART = 'UPDATE_LIST_CART'
export const DESTROY_CART = 'DESTROY_CART'

export const ADD_FAVORITE = 'ADD_FAVORITE'
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE'
export const REPLACE_LIST_FAVORITE = 'REPLACE_LIST_FAVORITE'

export const REPLACE_LIST_ORDER_LATER = 'REPLACE_LIST_ORDER_LATER'
export const ADD_ORDER_LATER = 'ADD_ORDER_LATER'
export const ADD_BACKTO_CART = 'ADD_BACKTO_CART'
export const REMOVE_ORDER_LATER = 'REMOVE_ORDER_LATER'
