export const FETCHING = "FETCHING";
export const UPDATE_LIST_PRODUCT = "UPDATE_LIST_PRODUCT";
export const LOAD_MORE = "LOAD_MORE";
export const SORT_PRODUCT = "SORT_PRODUCT";
export const GET_SORT_CONDITION = "GET_SORT_CONDITION";
